version: '3.8'

services:
  aapanel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aapanel
    restart: unless-stopped
    ports:
      - "7800:7800"  # Panel akses
      - "80:80"      # HTTP website
      - "443:443"    # HTTPS
      - "21:21"      # FTP (opsional)
      - "22:22"      # SSH (opsional)
    volumes:
      - ./data/wwwroot:/www/wwwroot
      - ./data/server_data:/www/server/data
      - ./data/vhost:/www/server/panel/vhost
    environment:
      - TZ=Asia/Jakarta
